version: 2.1
jobs:
  build:
    docker: 
      - image: cimg/node:14.10.1 
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - run: cp -r build /tmp/build
      - store_artifacts:
          path: /tmp/build
  test:
    docker:
      - image: cimg/node:14.10.1
    steps:
      - checkout
      - run: npm test --reporters=jest-junit --results-directory:test_results
      - store_test_results:
          path: /tmp/test_results