version: 2.1

executors:
  docker-publisher:
    environment:
      REACT: robertaro/restaurant-app
    docker:
      - image: circleci/buildpack-deps:stretch
      
jobs:
  build-and-test:
    docker: 
      - image: cimg/node:14.10.1 
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - run: npm test -- --maxWorkers=2 --logHeapUsage
      - run: cp -r build /tmp/build
      - store_artifacts:
          path: /tmp/build

  publish-latest:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run: |
            cd game-of-life && docker build -t $REACT:latest .
      - run: docker save -o image.tar $REACT
      - run: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $REACT:latest
            
workflows:
  build_and_test:
    jobs:
      - build-and-test:
          filters:
            branches:
              only: master
      - publish-latest:
          context: docker
          filters:
            branches:
              only: master
          requires:
            - build-and-test