version: 2.1
jobs:
  build:
    docker: 
      - image: cimg/node:14.10.1 
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - run: npm test --reporters=jest-junit
      - store_test_results
          path: coverage
      - run: cp -r build /tmp/build
      - store_artifacts:
          path: /tmp/build