version: 2.1
jobs:
  build:
    docker: 
      - image: cimg/node:15.0.1
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - run: 
          command: npm test --ci --reporters=default --reporters=jest-junit
          environment:
            NODE_OPTIONS=--max_old_space_size=8192
      - run: cp -r build /tmp/build
      - store_artifacts:
          path: /tmp/build
workflows:
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              only: master