version: 2.1
jobs:
  build:
    docker: 
      - image: cimg/node:14.10.1 
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - run: cp -r build /tmp/build
      - store_artifacts:
          path: /tmp/build
  test:
    docker:
      - image: cimg/node:14.10.1
    steps:
      - checkout
      - run: 
          command: npm test --reporters=jest-junit --results-directory:test_results
          environment:
            JEST_JUNIT_OUTPUT_DIR: ./reports/junit/
      - store_test_results:
          path: ./reports/junit/
workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build